{
	"version": 1741989690,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/lapiz-sheet0.png",
		"images/tinta-sheet0.png",
		"images/tinta-sheet1.png",
		"images/tinta-sheet2.png",
		"images/borrador-sheet0.png",
		"images/fondo-sheet0.png",
		"images/boton_procesar-sheet0.png",
		"images/lapiz2-sheet0.png",
		"images/muestra_tinta-sheet0.png",
		"images/muestra_tinta-sheet1.png",
		"images/muestra_tinta-sheet2.png",
		"images/flecha_continuar-sheet0.png",
		"images/boton_musica-sheet0.png",
		"images/boton_musica-sheet1.png",
		"images/digitos_sprite-sheet0.png",
		"images/digitos_sprite-sheet1.png",
		"images/digitos_sprite-sheet2.png",
		"images/up_arrow_sprite-sheet0.png",
		"images/down_arrow_sprite2-sheet0.png",
		"images/linea-sheet0.png",
		"media/aplausos.m4a",
		"media/aplausos.ogg",
		"media/aplausos_poder.m4a",
		"media/aplausos_poder.ogg",
		"media/revisa_respuesta_.m4a",
		"media/revisa_respuesta_.ogg",
		"media/kazoom - quincas moreira.m4a",
		"media/kazoom - quincas moreira.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"roar_guroes-webfont.woff",
		"roar_guroes-webfont.woff2",
		"stylesheet.css",
		"lapiz.png",
		"adapter.js"
	]
}